name: Python application

on:
  push:
    branches: [ master ]
    paths:
      - '**'
  pull_request:
    branches: [ master ]
    paths:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    - name: Build EXE
      run: |
        python -m pip install pyinstaller
        pyinstaller -F --noconsole --icon=images\\logo.ico use_main.py  # 使用 --icon 来指定图标文件

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-exe
        path: dist/use_main.exe  # 确保路径和文件名正确
